load("mitMap.mat");
subplot(2, 2, 1);
imagesc(mit);
colormap(cMap);
title('Square');
axis('square');
subplot(2, 2, 2);
imagesc(mit);
colormap(cMap);
title('Tight');
axis('tight');
subplot(2, 2, 3);
imagesc(mit);
colormap(cMap);
title('Equal');
axis('equal');
subplot(2, 2, 4);
imagesc(mit);
colormap(cMap);
title('XY');
axis('xy');